### PR TITLE
frontend dependency management, refresh tech base

### PR DESCRIPTION
**Pull request by nebulon42**
My intention with this PR is to start refreshing the technological base for the frontend. The changes will require a bit of explanation because on the first glance it may look like as it is getting more complicated and the question may arise why this is beneficial.

If this goes through my next steps would be to pull in Bootstrap and  remove jQuery Mobile and then slowly also start to refresh the visual appearance.

This site does not use many **JS dependencies**, but to make it easier to manage them and to pull in new ones I'd like to switch to **NPM for JS dependency management**. On the downside this requires Node.js and NPM for development, but on the upside updating a library needs only bumping the version number in `package.json` and installing a new one only needs `npm install --save xyz`. For this there is a `package.json` file in `frontend/static`.

The next update in this PR is to use **Sass instead of pure CSS**. The CSS here is not extensive (yet) but Sass makes it easier to write and maintain CSS by allowing nesting, inheritance, variables and so on. The downside is that Sass has to be compiled to CSS before it can be used by the browser.

Speaking of compiling this needs some sort of **task runner**. You have to be able to transform your Sass into CSS. That is where **Gulp** comes into play. Gulp is a task runner written in JavaScript. (All the dev dependencies are also managed by NPM in a `package.json` in the root directory.) To explain why JavaScript I have to say that the state of the art in frontend development nowadays is to do things in JavaScript.

But back to Gulp: You need to install the CLI globally by doing `npm install -g gulp-cli`. Then you can run `gulp css` in `frontend/static` and your Sass is
* compiled to CSS
* autoprefixed, that means vendor prefixes are added automatically if needed
* minified (in production: if you run `gulp css --production`)
* extended with source maps (if not in production)

You end up with a CSS in the `frontend/static/css` folder that can be used directly.

What are source maps? If you write your Sass which is then compiled to CSS and interpreted by the browser debugging gets more difficult. Errors are displayed in the CSS while you have to fix them in the Sass. That is why there are source maps. They map the CSS definitions back to Sass so that the developer tools of the browser can display the correct location of the error.

The last change in this PR is to **bundle external JS dependencies** together with **Webpack**. The Node.js way of writing JavaScript is to use `require` statements when pulling in other libraries. If this can be done in the Browser too then you are able to write modular and better maintainable JavaScript. For the external libraries that means that you do not have to reference them by hand or bundle them together by hand. For this there is a file `frontend/static/js/vendor.js` which is then transformed into a vendor bundle by Webpack and results in a `frontend/static/packed/vendor.js`.

The transformation is again done by gulp. If you run `gulp js` in the `frontend/static` folder this task is performed. To process both CSS and JS simultaneously you have to run just `gulp`.

Some concerns about **deployment**: I don't know how this is currently deployed to production, but with this change there need to be the following additional steps:
* have Node.js available
* run `npm install` in the root folder, this should also install the dependencies in the `frontend/static` folder if you are on *nix systems
* change to `frontend/static` and run `gulp --production`
* remove both `node_modules` folders as they can get large and are not needed on the server

**Open task:** I could not test if the switch to NPM regarding flot works because I had no graphs.

**Open question:** Do we need cssutils after this change?

### CODE REVIEW

**Comment by lonvia** [comment]
Thanks for the effort in going through all this code and for your thoughtful comments and explanations of your motivations. It is highly appreciated, still I kind of wish though, you had started a discussion beforehand.

The thing is that this is meant to be a Python project. Javascript only comes into play where it is absolutely unavoidable, i.e. for any code run in the browser. This is a personal choice and may or may not sound sensible to you but it is an invariant in this project that is not up for discussion.

So for that reason NPM/node.js are something I would like to avoid if anyhow possible. And for that reason, the frontend is based on Openlayers and JQuery Mobile. Those were the two libraries that offer everything the frontend needs without having to install and manage an endless series of incompatible plugins. (There are reasons to revisit that decision but  "because it's not what the cool kids use" is not one of them.)

So if you are interested in refreshing the frontend code, I would suggest a different way forward. I've spent a lot of time last year to give the project a proper restful API, so that it is possible to develop other applications and frontend. Let's make use of that functionality. I would suggest to add the option to run this code in API-only mode with my nice 90's frontend disabled. Then you can start to develop a new refreshed frontend in a separate repo, making only use of the API there. The new repo could also live under the umbrella of the previously suggested waymarked-trails orga. What do you think?

**Comment by nebulon42** [comment]
Thanks for the quick response. Yes, I had thought of discussing first, but then decided go for action instead. :) But don't worry I respect your choices as maintainer.

> because it's not what the cool kids use

I'm not sure if my explanations have suggested this, but I didn't want to sound it like that.

> So if you are interested in refreshing the frontend code, I would suggest a different way forward. I've spent a lot of time last year to give the project a proper restful API, so that it is possible to develop other applications and frontend.

Sounds like a good idea. Have not seen the API, so didn't know about that. Splitting frontend and backend part could have a lot of benefits but also some downsides.

The main question is if we can live with the consequences. Before a new frontend would be ready there is not much risk for the project. Just go on as before. After the switch the question is where most of the user requests will surface. I suspect in the frontend repo. Issues there would have to be triaged into frontend and backend changes and then referenced here accordingly. There is also the question if the frontend repository can be and will be properly maintained. If you as creator and main maintainer want not or can not deal with the frontend repository would it be beneficial for the project to start something like that?

**Comment by nebulon42** [comment]
I thought I try the following:

Since I now know that there is a API the frontend can be build independent from the backend. I will try to build something and we then can decide if it is worthwhile to move it to a waymarked-trails organisation and to switch the default frontend to the new technology. For development I will use the production API but I think that this has no impact on load. When there is something ready I will make it accessible via a server of mine which communicates with the production backend.

Is this ok?

**Comment by lonvia** [comment]
Sure, sounds good. The API currently lacks documentation, I need to change that. The entry point in the code is in `api/routes.py` but it is not exactly obvious what the endpoints are. It's probably easiest to have a look what the current frontend does. Also note that the current API is heavily geared toward the existing frontend. If you feel that it lacks information, feel free to open a ticket here.

To answer your previous questions about the future of a separate frontend, I'm not too worried about that. I am aware that at least part of the maintenance would fall on me but that's fine. I can find my way around Javascript to fix smaller bugs etc. and I can do anything backend-related. Still, I would ask you to keep in mind when starting this project that you should be prepared to be the principal maintainer for a longer period. If this is just about creating a new frontend and then moving on to the next project, then it may not be worth the time. I would also ask that you remember when writing the code that somebody else has to be able to read through it. So keep with best practices for node.js for writing maintainable code (I know that the node.js community has a lot to say on that subject) and carefully consider which external libraries you use as every library increases the maintenance effort. I'm sure this is all blatantly obvious to you, I just wanted to mention it anywhere as these will be the most important point for the technical decision if a new frontend goes into production.

In any case, I'm looking forward to see what you come up with. :)

**Pull request closed without merging**
